# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: development.log
email: keang@song.gg
description: > # this means to ignore newlines until "baseurl:"
  This serves as a log of things I've learnt or observed. I'm a software engineer who's still naive and optimistic, and eager to get my hands dirty with codes.
  I'd love to have a chat!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://log.keang.song.gg" # the base hostname & protocol for your site
twitter_username: skeang
github_username:  keang
timezone: Australia/Melbourne
permalink: /posts/:title:output_ext

# Build settings
markdown: kramdown
