var CONFIG = {};

CONFIG.BLOG_TITLE = "Keang's blog";
CONFIG.NAV_TITLE = "Keang's";

CONFIG.SHOW_SIDEBAR = true;
CONFIG.NUM_POSTS_IN_SIDEBAR = 5;
CONFIG.NUM_POSTS_PER_PAGE = 4;
CONFIG.ENABLE_ANIMATIONS = true;

CONFIG.USE_DISQUS = true;
CONFIG.DISQUS_SHORT_NAME = 'kakaka';
CONFIG.SITE_DOMAIN = 'keang.be/';